### ISSUE TITLE
Warnings, etc., in t_piSimpleTransforms

### ISSUE THREAD

**Issue by DavidBrainard** [ISET/iset3d#10]
We were able to install and run this tutorial!  Yay!  If you use ToolboxToolbox you can just type tbUse('iset3d') and all dependencies will be magically sucked down to your computer and put on your path.

A) However, we got this warning: 

Warning: Cannot find "filter" in PBRT file. 
> In piRead (line 195)
  In t_piSimpleTransforms (line 19) 
Warning: "Renderer" does not exist in the new PBRTv3 format. We leave the field blank . 
> In piRead (line 227)
  In t_piSimpleTransforms (line 19) 

Should we be worried?

B) The tutorial writes data onto the isetbio tree.  Should we check it in?  Probably not.  Probably things should be changed to write to tempdir or a "local" ignored directory within the tree.

**Comment by tlian7** [comment]
Hi @DavidBrainard,

Glad it runs for you! 

A) The warning is nothing to worry about - in fact we might just remove it since we're primarily using v3 nowadays. If you're curious, it's there because in PBRTv2 there is a "Renderer" parameter in the recipe which doesn't exist in PBRTv3. The recipe structure still has the variable around, but remains empty when we use v3.

B) Whenever we render with sceneEye the working directory is written into a local folder in ISETBio. I thought that made sense, since sceneEye is primarily an ISETBio class but uses ISET3d underneath the hood to render. I usually just manually ignore the local folder in Git. Let me know if you think that's alright, otherwise we can also stick it in ISET3d. Or is there a way to automatically git ignore the folder when it's created?

**Comment by DavidBrainard** [comment]
It is writing into data/V3/coloredCube, in iset3D, modifying the file coloredCube.json.

And t_piExample_SceneAssembly writes into data/V3/checkerboard, before it crashes.

Should data also be git ignored?  Or should this output stuff go into the local tree instead?

**Comment by tlian7** [comment]
So @Zhenyi-Liu can probably speak more to this, but I believe those extra JSON and material files are written to faciliate the interaction between the large simulated driving scenes and the cloud system. We’ve discussed previously that we would like to write these files somewhere else (probably to the local directory,) so I think in the future those extra files won’t be an issue once the changes are made.

**Comment by Zhenyi-Liu** [comment]
This is a typical output of geometry.pbrt exported from c4d(I can share the plugin later):
```
AttributeBegin

   #ObjectName Cube:Vector(10, 10, 10)
   ConcatTransform [1.0 0.0 0.0 0  0.0 1.0 0.0 0  0.0 0.0 1.0 0  23.2946776584 0.0 191.803232641 1]
   AttributeBegin
	NamedMaterial "cube_material"
         Shape "trianglemesh"  "integer indices" [0 1 2 2 3 0 4 5 6 6 7 4 8 9 10 10 11 8 12 13 14 14 15 12 16 17 18 18 19 16 20 21 22 22 23 20 ] 
         "point P" [-10.0 0.188180036279 -10.0 -10.0 20.1881800363 -10.0 10.0 20.1881800363 -10.0 10.0 0.188180036279 -10.0 10.0 0.188180036279 -10.0 10.0 20.1881800363 -10.0 10.0 20.1881800363 10.0 10.0 0.188180036279 10.0 10.0 0.188180036279 10.0 10.0 20.1881800363 10.0 -10.0 20.1881800363 10.0 -10.0 0.188180036279 10.0 -10.0 0.188180036279 10.0 -10.0 20.1881800363 10.0 -10.0 20.1881800363 -10.0 -10.0 0.188180036279 -10.0 -10.0 20.1881800363 -10.0 -10.0 20.1881800363 10.0 10.0 20.1881800363 10.0 10.0 20.1881800363 -10.0 -10.0 0.188180036279 10.0 -10.0 0.188180036279 -10.0 10.0 0.188180036279 -10.0 10.0 0.188180036279 10.0 ] 
         "float uv" [0.0 -1.0 0.0 0.0 1.0 0.0 1.0 -1.0 0.0 -1.0 0.0 0.0 1.0 0.0 1.0 -1.0 0.0 -1.0 0.0 0.0 1.0 0.0 1.0 -1.0 0.0 -1.0 0.0 0.0 1.0 0.0 1.0 -1.0 0.0 -1.0 0.0 0.0 1.0 0.0 1.0 -1.0 0.0 -1.0 0.0 0.0 1.0 0.0 1.0 -1.0 ] 
         "normal N" [0.0 0.0 -1.0 0.0 0.0 -1.0 0.0 0.0 -1.0 0.0 0.0 -1.0 1.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 1.0 -1.0 0.0 0.0 -1.0 0.0 0.0 -1.0 0.0 0.0 -1.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 -1.0 0.0 0.0 -1.0 0.0 0.0 -1.0 0.0 0.0 -1.0 0.0 ]
	AttributeEnd
AttributeEnd
```
`Vector(10, 10, 10)`(radius) is the size of the object, and we can kown it's a cube in this case;
`cancatTransform [...]` contains the translation, rotation and scale information of the object.
```
Shape "trianglemesh"  "integer indices"[...]
"point P" [....]
"float uv" [...]
"normal N" [...]
```
This part is what we consider as the geometry information, and we save it as a sperate file, after that we write out a new geometry file in a way as below:
```
AttributeBegin
Translate 23.2946776584 0.0 191.803232641 
Rotate 0.000000 1.000000 0.000000 0.000000
Rotate 0.000000 0.000000 1.000000 0.000000
Rotate 0.000000 0.000000 0.000000 1.000000
ObjectInstance "cube"
AttributeEnd

ObjectBegin "cube"
NamedMaterial "cube_material"
Include "scene/PBRT/pbrt-geometry/cube.pbrt"
ObjectEnd
```
Thus, at the end, we will have a much much smaller geometry file, it will be less painful to look into the file when we have hundreds of 3d objects in the scene. 
In ISET3d, piRead calls piGeometryRead, and piGeometryRead generates a scene folder and a textures folder, an extra json file saves the current recipe which is helpful for me when I don't want to wait for a very large 3d object to load again and again.
