### ISSUE TITLE
v_iset3d broken

### ISSUE THREAD

**Issue by DavidBrainard** [ISET/iset3d#13]
The validation script runs for a while and does lots of seemingly good things, but then crashes for me, with the error line being:

t_piMaterials: Takes a minute or two
Error using t_piMaterials (line 19)
File not found

Error in v_iset3d (line 18)
t_piMaterials
 
Also note that at least some of what this is doing involves pbrt_v2 not pbrt_v3.

**Comment by wandell** [comment]
The new validation script is t_renderAllScenes, tested with ISETBio (not ISETCam).

We will add a v_ISET3DCam based on the tutorials in the near future.  Closing this.
