### ISSUE TITLE
piTrafficPlace, piSceneAuto have git merge stray text.

### ISSUE THREAD

**Issue by DavidBrainard** [ISET/iset3d#19]
There's some of that "<<<<< HEAD" sort of stuff in these two files.  I believe it has been there for at least a little while, because a file history check indicates last change around November 9. That is, I don't think this relates to things I have done in the last few days.

**Comment by Zhenyi-Liu** [comment]
@DavidBrainard Hi David, the stray text has been removed, thanks for checking on this.
