### ISSUE TITLE
s_ versus t_

### ISSUE THREAD

**Issue by DavidBrainard** [ISET/iset3d#24]
I continue to be baffled by what conceptual distinction scrips are sorted into s_ and t_ scripts.

**Comment by wandell** [comment]
The scripts were supposed to be interesting examples of calculations that we might want to share with others.  The tutorials were supposed to be real training cases with explanatory text.  As your comment makes clear, there is no bright line between scripts and tutorials.  A beautifully commented script could be a tutorial.  A lousy tutorial should be a script.

Not sure what we should do about this.  I continue to think, however, that we need tutorials.  Should we create ISETBio-scripts and only move something into ISETBio when it is a tutorial?  In a way, the scripts directory serves that purpose already.  Continuing the bafflement ....

**Comment by DavidBrainard** [comment]
Thanks.  I am beginning to understand the concept. Agree that it is tricky to know exactly how to divide the continuum. Something to discuss, maybe with Jenn as well.

We experimented in IBIOColorDetect with making tutorials callable functions that could do actual work with the right arguments, but that had defaults that did something simple and illustrative.  But I think maybe in then end that made them too hard as tutorials, as they started to get pretty complex.   At the same time, making them functions seemed like a step in the direction of minimizing code duplication.
