### ISSUE TITLE
iset3d peripheral blurring

### ISSUE THREAD

**Issue by benjaminralex** [ISET/iset3d#47]
A question about the rendering. Does it simulate the fact that the perhipheral vision has a much lower resolution than the central vision? i.e. there is peripheral blurring?

Thank you!

**Comment by wandell** [comment]
The off-axis blurring is whatever the folks who provide the model specified.  But those models were not designed to handle the periphery, so although the ray tracing follows the models, the models are not good at off-axis.

If this is of interest to you, I suggest you have a look at the ISETBio demoapps.  Nicolas Cottaris has implemented lots of calculations that address the blur and sampling as a function of eccentricity.  Those are mainly for planar scenes or 3D scenes where everything is far away.  But the question of blur as a function of eccentricity is really taken seriously there.

**Comment by benjaminralex** [comment]
Thank you! Much apprecaited.
